var software_list = [
  {
    "name": "Hitman",
    "year": 2016,
    "min_cpu": "Intel CPU Core i5-2500K 3.3GHz",
    "min_gpu": "NVIDIA GeForce GTX 660",
    "rec_cpu": "Intel CPU Core i7 3770 3,4 GHz",
    "rec_gpu": "Nvidia GPU GeForce GTX 770",
    "min_RAM_GB": 8,
    "max_RAM_GB": 8,
    "min_cpu_bench": 6456,
    "min_gpu_bench": 4121,
    "rec_cpu_bench": 9343,
    "rec_gpu_bench": 6148
  },
  {
    "name": "Crysis",
    "year": 2007,
    "min_cpu": "Intel Pentium 4 2.8 GHz",
    "min_gpu": "NVIDIA GeForce 6800 GT",
    "rec_cpu": "Core 2 Duo 2.2 GHz",
    "rec_gpu": "NVIDIA GeForce 8800 GTS",
    "min_RAM_GB": 1,
    "max_RAM_GB": 2,
    "min_cpu_bench": 326,
    "min_gpu_bench": 101,
    "rec_cpu_bench": 1276,
    "rec_gpu_bench": 616
  },
  {
    "name": "Crysis 3",
    "year": 2013,
    "min_cpu": "Intel Core 2 Duo E4300**",
    "min_gpu": "Geforce GTS 450",
    "rec_cpu": "Intel Core 2 Quad Q6600 @ 2.40GHz**",
    "rec_gpu": "Geforce GTX 560",
    "min_RAM_GB": 3,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1054,
    "min_gpu_bench": 1546,
    "rec_cpu_bench": 2988,
    "rec_gpu_bench": 3111
  },
  {
    "name": "The Witcher 3: Wild Hunt",
    "year": 2015,
    "min_cpu": "Intel CPU Core i5-2500K 3.3GHz",
    "min_gpu": "Nvidia GPU GeForce GTX 660",
    "rec_cpu": "Intel CPU Core i7 3770 3.4 GHz",
    "rec_gpu": "Nvidia GPU GeForce GTX 770",
    "min_RAM_GB": 6,
    "max_RAM_GB": 8,
    "min_cpu_bench": 6456,
    "min_gpu_bench": 4121,
    "rec_cpu_bench": 9343,
    "rec_gpu_bench": 6148
  },
  {
    "name": "Grand Theft Auto 5",
    "year": 2015,
    "min_cpu": "Intel Core 2 Quad CPU Q6600",
    "min_gpu": "NVIDIA GeForce 9800 GT 1GB",
    "rec_cpu": "Intel Core i5 3470 @ 3.2GHZ",
    "rec_gpu": "NVIDIA GeForce GTX 660 2GB",
    "min_RAM_GB": 4,
    "max_RAM_GB": 8,
    "min_cpu_bench": 2988,
    "min_gpu_bench": 726,
    "rec_cpu_bench": 6567,
    "rec_gpu_bench": 4121
  },
  {
    "name": "The Sims 4",
    "year": 2014,
    "min_cpu": "Intel Core 2 Duo E4300",
    "min_gpu": "NVIDIA GeForce 6600",
    "rec_cpu": "Intel Core i5-750",
    "rec_gpu": "NVIDIA GeForce GTX 650",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1054,
    "min_gpu_bench": 63,
    "rec_cpu_bench": 3733,
    "rec_gpu_bench": 1831
  },
  {
    "name": "Battlefield 3",
    "year": 2013,
    "min_cpu": "Core 2 Duo 2.4 GHz or Athlon X2 2.7 GHz",
    "min_gpu": "NVIDIA GeForce 8800 GT",
    "rec_cpu": "QUAD-CORE",
    "rec_gpu": "NVIDIA GeForce GTX 560",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1388,
    "min_gpu_bench": 760,
    "rec_cpu_bench": 2988,
    "rec_gpu_bench": 3111
  },
  {
    "name": "Batman: Arkham Asylum",
    "year": 2009,
    "min_cpu": "Intel Pentium 4 3.0 GHz or AMD Athlon 64 3500+",
    "min_gpu": "NVIDIA GeForce 6600",
    "rec_cpu": "Core 2 Duo E6600 (2.4 GHz) or AMD Athlon 64 X2 4600+",
    "rec_gpu": "NVIDIA GeForce 7900 GT or better",
    "min_RAM_GB": 2,
    "max_RAM_GB": 3,
    "min_cpu_bench": 357,
    "min_gpu_bench": 63,
    "rec_cpu_bench": 1560,
    "rec_gpu_bench": 258
  },
  {
    "name": "Batman: Arkham Origins",
    "year": 2013,
    "min_cpu": "Intel Core Duo, 2.4 GHz",
    "min_gpu": "NVIDIA GeForce 8800 GTS",
    "rec_cpu": "Intel Core i5 750, 2.67 GHz",
    "rec_gpu": "NVIDIA GeForce GTX 560",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1560,
    "min_gpu_bench": 616,
    "rec_cpu_bench": 2197,
    "rec_gpu_bench": 3111
  },
  {
    "name": "Tomb Raider",
    "year": 2013,
    "min_cpu": "AMD Athlon64 X2 2.1 Ghz (4050+)",
    "min_gpu": "Radeon HD 2600ÿ",
    "rec_cpu": "AMD Phenom II x2 565",
    "rec_gpu": "Radeon HD 4870",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1042,
    "min_gpu_bench": 218,
    "rec_cpu_bench": 2188,
    "rec_gpu_bench": 1375
  },
  {
    "name": "World of Warcraft",
    "year": 2005,
    "min_cpu": "Intel Core 2 Duo E6600 or AMD Phenom X3 8750",
    "min_gpu": "NVIDIA GeForce 8800 GT",
    "rec_cpu": "Intel Core i5 2400",
    "rec_gpu": "NVIDIA GeForce GTX 470",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1560,
    "min_gpu_bench": 760,
    "rec_cpu_bench": 5836,
    "rec_gpu_bench": 3582
  },
  {
    "name": "Portal 2",
    "year": 2007,
    "min_cpu": "Dual Core 2.0 (or higher)",
    "min_gpu": "GeForce 7600",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 2,
    "max_RAM_GB": "null",
    "min_cpu_bench": 1147,
    "min_gpu_bench": 182,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Goat simulator",
    "year": 2014,
    "min_cpu": "2.0 GHz Dual Core Processor",
    "min_gpu": "Shader Model 3.0-compatible 256 VRAM",
    "rec_cpu": "2.0 GHz Quad Core Processor",
    "rec_gpu": "NVIDIA GeForce 8800 GTS",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1147,
    "min_gpu_bench": "null",
    "rec_cpu_bench": 2344,
    "rec_gpu_bench": 616
  },
  {
    "name": "DiRT 3",
    "year": 2011,
    "min_cpu": "AMD Athlon? 64 X2 2.8 GHz",
    "min_gpu": "AMD Radeon? HD 2000 256 MB",
    "rec_cpu": "AMD Phenom? II or Intel? Core? i7",
    "rec_gpu": "AMD Radeon? HD 6000 Series",
    "min_RAM_GB": 2,
    "max_RAM_GB": 3,
    "min_cpu_bench": 1447,
    "min_gpu_bench": 301,
    "rec_cpu_bench": 8267,
    "rec_gpu_bench": 117
  },
  {
    "name": "Project Cars",
    "year": 2015,
    "min_cpu": "Intel Core 2 Quad Q8400",
    "min_gpu": "NVIDIA GeForce GTX 260",
    "rec_cpu": "Intel Core i7 3700 or AMD FX-8350",
    "rec_gpu": "NVIDIA GeForce GT 650",
    "min_RAM_GB": 4,
    "max_RAM_GB": 8,
    "min_cpu_bench": 2660,
    "min_gpu_bench": 1118,
    "rec_cpu_bench": 8951,
    "rec_gpu_bench": 1203
  },
  {
    "name": "Starcraft II",
    "year": 2010,
    "min_cpu": "Intel Core 2 Duo or AMD Athlon 64 X2 5600+",
    "min_gpu": "NVIDIA GeForce 7600 GT",
    "rec_cpu": "Intel Core i5 or AMD FX Series Processor or better",
    "rec_gpu": "NVIDIA GeForce GTX 650",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1481,
    "min_gpu_bench": 182,
    "rec_cpu_bench": 2197,
    "rec_gpu_bench": 1831
  },
  {
    "name": "EVE Online",
    "year": 2003,
    "min_cpu": "Intel Dual Core @ 2.0 GHz",
    "min_gpu": "NVIDIA GeForce 8600 GTS",
    "rec_cpu": "Intel i7 Series or AMD X4 @ 2.0 GHz or greater",
    "rec_gpu": "NVIDIA GeForce GTX 560",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1147,
    "min_gpu_bench": 301,
    "rec_cpu_bench": 8267,
    "rec_gpu_bench": 3111
  },
  {
    "name": "Runescape",
    "year": 2007,
    "min_cpu": "Intel Pentium, Intel Celeron, Intel Core and Intel Mobile or AMD Mobile series/single and Dual core.",
    "min_gpu": "GeForce 4",
    "rec_cpu": "Intel i5 or i7 / AMD Athlon X2 or better",
    "rec_gpu": "ATI Radeon HD (non M or Mobility) / nVidia GeForce 1xx/2xx/3xx/4xx/5xx/6xx (excluding M / Mobile or Go)",
    "min_RAM_GB": 1,
    "max_RAM_GB": 4,
    "min_cpu_bench": 131,
    "min_gpu_bench": 229,
    "rec_cpu_bench": 2197,
    "rec_gpu_bench": 124
  },
  {
    "name": "Maple Story",
    "year": 2015,
    "min_cpu": "Intel Core 2 Duo 2.4Ghz",
    "min_gpu": "GeForce 8600 GT",
    "rec_cpu": "Intel Core 2 Duo 3.0Ghzÿ",
    "rec_gpu": "GeForce 9600 GT",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1560,
    "min_gpu_bench": 253,
    "rec_cpu_bench": 1970,
    "rec_gpu_bench": 750
  },
  {
    "name": "The Elder Scrolls V: Skyrim",
    "year": 2011,
    "min_cpu": "Dual Core 2.0 GHz or equivalent processor",
    "min_gpu": "NVIDIA GeForce 7600 GT",
    "rec_cpu": "Quad-core Intel or AMD CPU",
    "rec_gpu": "NVIDIA GeForce GTX 260",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1147,
    "min_gpu_bench": 182,
    "rec_cpu_bench": 2988,
    "rec_gpu_bench": 1118
  },
  {
    "name": "Dragon Age Origins",
    "year": 2009,
    "min_cpu": "Intel Core 2 (or equivalent) running at 1.4 GHz or greater",
    "min_gpu": "128 MB NVIDIA GeForce 6600 GT",
    "rec_cpu": "Intel Core 2 Quad 2.4 GHz Processor or equivalent",
    "rec_gpu": "NVIDIA GeForce 8800 GTS",
    "min_RAM_GB": 1,
    "max_RAM_GB": 4,
    "min_cpu_bench": 1054,
    "min_gpu_bench": 63,
    "rec_cpu_bench": 2988,
    "rec_gpu_bench": 616
  },
  {
    "name": "Lightning Returns: Final Fantasy XIII",
    "year": 2015,
    "min_cpu": "2GHz Dual Core CPU",
    "min_gpu": "NVIDIA Geforce 8800GT",
    "rec_cpu": "Intel Core 2 Quad (2.66 GHz)",
    "rec_gpu": "NVIDIA Geforce GTX 460",
    "min_RAM_GB": 1.5,
    "max_RAM_GB": 2,
    "min_cpu_bench": 1147,
    "min_gpu_bench": 760,
    "rec_cpu_bench": 3228,
    "rec_gpu_bench": 2642
  },
  {
    "name": "Unity Games",
    "year": "null",
    "min_cpu": "null",
    "min_gpu": "Graphics card with DX9 (shader model 2.0) capabilities. Anything made since 2004 should work.",
    "rec_cpu": "null",
    "rec_gpu": "Graphics card with DX9 (shader model 2.0) capabilities. Anything made since 2004 should work.",
    "min_RAM_GB": "null",
    "max_RAM_GB": "null",
    "min_cpu_bench": "null",
    "min_gpu_bench": 21,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": 21
  },
  {
    "name": "Unity Game Development",
    "year": "null",
    "min_cpu": "null",
    "min_gpu": "Graphics card with DX9 (shader model 2.0) capabilities. Anything made since 2004 should work.",
    "rec_cpu": "null",
    "rec_gpu": "Graphics card with DX9 (shader model 2.0) capabilities. Anything made since 2004 should work.",
    "min_RAM_GB": "null",
    "max_RAM_GB": "null",
    "min_cpu_bench": "null",
    "min_gpu_bench": 21,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": 21
  },
  {
    "name": "Unreal Engine 4 Development",
    "year": "null",
    "min_cpu": "Quad-core Intel or AMD processor, 2.5 GHz or faster",
    "min_gpu": "NVIDIA GeForce 470 GTX",
    "rec_cpu": "Intel Core i7 4930K processor",
    "rec_gpu": "Nvidia GTX 770",
    "min_RAM_GB": 8,
    "max_RAM_GB": 32,
    "min_cpu_bench": 2988,
    "min_gpu_bench": 3582,
    "rec_cpu_bench": 13056,
    "rec_gpu_bench": 6148
  },
  {
    "name": "Adobe Premiere",
    "year": 2015,
    "min_cpu": "Intel Core2 Duo or AMD Phenom II processor with 64-bit support",
    "min_gpu": "null",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 4,
    "max_RAM_GB": 8,
    "min_cpu_bench": 1054,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Photoshop CC 2015",
    "year": 2015,
    "min_cpu": "Intel? Core 2 or AMD Athlon? 64 processor; 2ÿGHz or faster processor",
    "min_gpu": "null",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 2,
    "max_RAM_GB": 8,
    "min_cpu_bench": 1054,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Microsoft Office 2013",
    "year": 2013,
    "min_cpu": "1 gigahertz (GHz) or faster x86- or x64-bit processor with SSE2 instruction set",
    "min_gpu": "DX10 GPU",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 2,
    "max_RAM_GB": "null",
    "min_cpu_bench": 241,
    "min_gpu_bench": 616,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Visual Studio Community 2015",
    "year": 2015,
    "min_cpu": "1.6 GHz or faster processor",
    "min_gpu": "DX9 GPU",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 1,
    "max_RAM_GB": "null",
    "min_cpu_bench": 131,
    "min_gpu_bench": 21,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Android Studio",
    "year": 2013,
    "min_cpu": "null",
    "min_gpu": "null",
    "rec_cpu": "Intel? processor with support for Intel? VT-x, Intel? EM64T (Intel? 64), and Execute Disable (XD)",
    "rec_gpu": "null",
    "min_RAM_GB": 2,
    "max_RAM_GB": 4,
    "min_cpu_bench": 0,
    "min_gpu_bench": 0,
    "rec_cpu_bench": 8267,
    "rec_gpu_bench": "null"
  },
  {
    "name": "Windows 95",
    "year": 1995,
    "min_cpu": "386DX or higher processor (486 recommended)",
    "min_gpu": "null",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 0.00390625,
    "max_RAM_GB": 0.0078125,
    "min_cpu_bench": 0,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Windows 98",
    "year": 1998,
    "min_cpu": "486DX 66 megahertz (MHz)",
    "min_gpu": "null",
    "rec_cpu": "null",
    "rec_gpu": "ATI All-in-Wonder graphics card",
    "min_RAM_GB": 0.015625,
    "max_RAM_GB": 0.0234375,
    "min_cpu_bench": 14,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": 4
  },
  {
    "name": "Windows XP",
    "year": 2001,
    "min_cpu": "Processor speed (MHz) 233",
    "min_gpu": "null",
    "rec_cpu": "Processor speed (MHz) 300+",
    "rec_gpu": "null",
    "min_RAM_GB": 0.0625,
    "max_RAM_GB": 0.125,
    "min_cpu_bench": 49,
    "min_gpu_bench": 0,
    "rec_cpu_bench": 73,
    "rec_gpu_bench": "null"
  },
  {
    "name": "Windows Vista - Home Premium",
    "year": 2007,
    "min_cpu": "1-gigahertz (GHz) 32-bit (x86) processor or 1-GHz 64-bit (x64) processor",
    "min_gpu": "128MB of Graphics memory",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 1,
    "max_RAM_GB": "null",
    "min_cpu_bench": 241,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Windows 7",
    "year": 2009,
    "min_cpu": "1 gigahertz (GHz) or faster 32-bit (x86) or 64-bit (x64) processor*",
    "min_gpu": "DX9 GPU",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 1,
    "max_RAM_GB": 2,
    "min_cpu_bench": 241,
    "min_gpu_bench": 21,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Windows 8.1",
    "year": 2013,
    "min_cpu": "1 gigahertz (GHz)* or faster with support for PAE, NX, and SSE2 (more info)",
    "min_gpu": "DX9 GPU",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 1,
    "max_RAM_GB": 2,
    "min_cpu_bench": 241,
    "min_gpu_bench": 21,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Windows 10",
    "year": 2015,
    "min_cpu": "1 gigahertz (GHz)* or faster with support for PAE, NX, and SSE2 (more info)",
    "min_gpu": "DX9 GPU",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 1,
    "max_RAM_GB": 2,
    "min_cpu_bench": 241,
    "min_gpu_bench": 21,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Linux Mint",
    "year": "null",
    "min_cpu": "x86 processor (Linux Mint 64-bit requires a 64-bit processor. Linux Mint 32-bit works on both 32-bit and 64-bit processors).",
    "min_gpu": "null",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 0.5,
    "max_RAM_GB": 1,
    "min_cpu_bench": 130,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  },
  {
    "name": "Ubuntu",
    "year": "null",
    "min_cpu": "700 MHz processor (about Intel Celeron or better)",
    "min_gpu": "null",
    "rec_cpu": "null",
    "rec_gpu": "null",
    "min_RAM_GB": 0.5,
    "max_RAM_GB": 1,
    "min_cpu_bench": 130,
    "min_gpu_bench": 0,
    "rec_cpu_bench": "null",
    "rec_gpu_bench": "null"
  }
];